### ISSUE TITLE
TFT

### ISSUE THREAD

**Issue by Semenov-Alexander** [jehy/co2-online-display#3]
Здравствуйте! 
Не пробовали реализовать индикацию на TFT экране такого же круглого индикатора как на вебе со стрелкой и сегментами? Есть экран 1.8" SPI 128x160 
https://voltiq.ru/shop/tft-spi-display-1-8-inch-128-160-px/
Не могли бы под него адаптировать код?

**Comment by jehy** [comment]
Добрый день. Не, не пробовал, "я его слепила из того что было". Но под такие штуки есть ардуиновские библиотеки, вряд ли это сложно - но для меня спортивного интереса не вызывает :)

**Comment by Semenov-Alexander** [comment]
Согласен, перевести на 7735 библиотеку можно, например графику как подложку, а вот стрелку рисовать по значению, вот где у меня проблема.
Кстати, в веб "co2-online-display" в инструкции написано:
2. Copy file db.inc.sample to db.inc and put there your database credentials.
Но файла db.inc.sample нет.... Или я не правильно понял?

**Comment by jehy** [comment]
Да, графика как подложка и стрелка типа так https://forum.arduino.cc/t/tft-lcd-analog-gauge/210357

Ридми поправил - я сначала делал inc файлы, потом привёл это к общему стандарту.
